In [10]:
#pip install pandas
#pip install numpy

In [11]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_csv("D:\SMS_Spam_Detection\sms-spam.csv")

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\Maheswari\AppData\Local\Temp\ipykernel_20332\116293165.py:1: SyntaxWarning: invalid escape sequence '\S'
  df=pd.read_csv("D:\SMS_Spam_Detection\sms-spam.csv")

In [13]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [14]:
df.tail()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [15]:
df.sample(3)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
3748,spam,Dear Voucher Holder 2 claim your 1st class air...,NaN,NaN,NaN
1125,spam,For taking part in our mobile survey yesterday...,NaN,NaN,NaN
407,ham,Hello! Good week? Fancy a drink or something l...,NaN,NaN,NaN

In [16]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [17]:
df.drop(columns=[ 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],inplace=True)

In [18]:
df.rename(columns={'v1':'result','v2':'message'},inplace=True)

In [19]:
df.head()

  result                                            message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [20]:
df['message']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: message, Length: 5572, dtype: object

In [21]:
df['result'].value_counts()

result
ham     4825
spam     747
Name: count, dtype: int64

In [22]:
df.isnull().sum()

result     0
message    0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(403)

In [24]:
df=df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [28]:
df['result'].count()

np.int64(5169)

In [35]:
df=df.replace({'ham':1,'spam':0})
df.head()

   result                                            message
0       1  Go until jurong point, crazy.. Available only ...
1       1                      Ok lar... Joking wif u oni...
2       0  Free entry in 2 a wkly comp to win FA Cup fina...
3       1  U dun say so early hor... U c already then say...
4       1  Nah I don't think he goes to usf, he lives aro...

In [43]:
for x in df:
    if(x['result']==1):
    print('h')

IndentationError: expected an indented block after 'if' statement on line 2 (2809407206.py, line 3)